name: 构建并上传Javadocker镜像

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build the Docker image
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} ghcr.io
          cd ruoyi-admin
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag ghcr.io/kdyzm/swagger-register-server:v1.0
          # 推送镜像到镜像仓库
          docker push ghcr.io/kdyzm/swagger-register-server:v1.0